language: php
php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'
- 'nightly'
before_script:
- autoreconf -f -i
script:
- ./configure && make && make check
addons:
  apt:
    packages:
    - autoconf
    - automake
branches:
  except:
  - master
