        <footer>
            <ul>
                <li><a href="/about">About the BBC</a></li>
                <li><a href="/accessibility">Accessibility help</a></li>
                <li><a href="/contact">Get in touch</a></li>
                <li><a href="/jobs">Jobs</a></li>
                <li><a href="/developers">Developers</a></li>
                <li><a href="/guidance">Parental guidance</a></li>
                <li><a href="/terms">Terms of use</a></li>
                <li><a href="/privacy">Privacy policy</a></li>
                <li><a href="/cookies">Cookies</a></li>
            </ul>
            <p><small><strong><a class="definition" href="/copyrightaware" title="Learn more about what copyright means">Copyright</a> © <?php echo strftime('%Y'); ?> BBC</strong>. The BBC is not responsible for the content of external sites. <a href="/help/web/links">Read about our approach to external linking</a>.</small></p>
            <p><small>Built by <a href="/about/departments/design-and-engineering">BBC Design and Engineering</a> and powered by <a href="https://github.com/bbc/alpha">open source software</a>, but only some of the content may be modified and redistributed. <a href="/terms">Find out more</a> about what you can download, modify and share.</small></p>
        </footer>
    </body>
</html>
<!-- <?php echo 'Page generated in ' . round(microtime(true)-$profile_start, 8) . 'ms'; ?> -->
