<?php 

/* Author: Mo McRoberts <mo.mcroberts@bbc.co.uk>
 *
 * Copyright (c) 2017 BBC
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/* This is the page template for the BBC homepage */

require(dirname(__FILE__) . '/_head.phtml');

?>

        <main>
            <h1>Welcome to the BBC</h1>
            
            <section>
                <h2>This is a section</h2>
            </section>

            <?php echo $components['boilerplate']; ?>

            <section class="key">
                <h2>Important section</h2>
            </section>

            <section>
                <h2>Another another section</h2>
            </section>

            <section class="bottom">
                <h2>Final section</h2>
            </section>
            
        </main>

<?php

require(dirname(__FILE__) . '/_foot.phtml');

